name = "stokes-headingley-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "860ba072deff4a49b1ecc6ed9e139a43"
preview_id = "860ba072deff4a49b1ecc6ed9e139a43"

[vars]
MAX_RUNS = "73"
MAX_BALLS = "96"
